language: generic
sudo: required 
services: 
  - docker 

before_install: 
  - docker build -t fjswayze/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true fjswayze/docker-react npm run test -- --coverage